; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ttgo]
platform = espressif32
board = ttgo-lora32-v2
framework = arduino
build_flags = -Ilib -Isrc -D LILYGO_TTGO_LORA32_V2 -D MY_NODE_ID=30
lib_deps = 
    adafruit/Adafruit SSD1306@^2.5.13
    adafruit/Adafruit GFX Library@^1.11.11
    adafruit/Adafruit BusIO@^1.17.0
    SPI
    Wire
    ./ext/RadioHead-master.zip

[env:m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
board_build.mcu = samd21g18a
board_build.f_cpu = 48000000L
upload_protocol = sam-ba
build_flags = -Ilib -Isrc -D ADAFRUIT_FEATHER_M0
lib_deps = 
    Wire
    SPI
    ./ext/RadioHead-master.zip

[env:rpi]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = adafruit_feather
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
upload_protocol = picotool
build_flags = -Ilib -Isrc -D ARDUINO_ADAFRUIT_FEATHER_RP2040_RFM
lib_deps = 
    Wire
    SPI
    ./ext/RadioHead-master.zip
